server:
  port: 8088

spring:
  datasource:
    platform: ${SPRING_DATASOURCE_PLATFORM}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: ${SPRING_DATASOURCE_DRIVER}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework: info
      hibernate:
        orm:
          jdbc:
            bind: trace