apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-quick-serve-db-claim
  labels:
    app: pvc-quick-serve-db
spec:
  storageClassName: local-storage  # Specify the storage class name if applicable
  accessModes:
    - ReadWriteMany  # Can be ReadWriteOnce, ReadOnlyMany, ReadWriteMany
  resources:
    requests:
      storage: 5Gi  # Size of storage requested, adjust as needed